#!/data/data/com.termux/files/usr/bin/bash

## Author : ABHacker Official
#copyrights free [2020]

#checking packages
command -v tput > /dev/null 2>&1 || { apt install ncurses-utils &> /dev/null ; clear ; connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m[\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi; }

command -v figlet > /dev/null 2>&1 || { echo -e >&2 "\033[1;91mI require figlet but it's not installed, Now Installing.\e[0m"; pkg install figlet -y; clear; connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m                             [\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi; }

#checking connection
connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then clear
echo -e "\033[1;91m                             [\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
   exit
fi

rm setup
#main progress
echo
tput civis
echo -e "\e[1m[⬇] Installing FONTS-F..."
cd $PREFIX/share
git clone https://github.com/abhackerofficial/FONTS-F > /dev/null 2>&1

#configure
if [ ! -f "$PREFIX/bin/show-figlet" ]; then
echo "cd $PREFIX/share/figlet && ls" > show-figlet
chmod +x show-figlet
mv show-figlet $PREFIX/bin
fi
if [ -f "$PREFIX/bin/show-figlet" ]; then
#continue main progress
echo
sleep 1
echo -e "\e[1m[!] Moving Fonts to Directory :- usr/share/figlet"
cd FONTS-F
rm setup && rm LICENSE && rm README.md
mv * $PREFIX/share/figlet
cd $HOME
rm -rf $PREFIX/share/FONTS-F
sleep 1
echo
echo -e "\e[1m[√] Setup Completed."
sleep 1
echo
echo -e "\e[1m[?] You can check exits Fonts Using :- show-figlet"
echo
echo -e "\e[1m[?] You can execute Fonts Using :-  figlet -f font-name 'test!' \e[0m"
echo
termux-reload-settings
tput cnorm
fi
#done (:
