#!/data/data/com.termux/files/usr/bin/bash

## Author : ABHacker Official

echo -e "\e[1m[⬇] Installing FONTS-F..."
cd $PRRFIX/share
git clone https://github.com/abhackerofficial/FONT-F &> /dev/null
sleep 1
echo
echo -e "\e[1m[!] Moving Fonts to Directory : usr/share/figlet
cd FONT-F
rm setup && LICENSE
mv * $PREFIX/share/figlet
cd $HOME
rm -rf $PREFIX/share/FONT-F
echo -e "\e[1m[√] Setup Completed."
sleep 1
echo
echo -e "\e[1m[?] You can execute Fonts Using :-  figlet -f font-name 'test!' \e[0m"
echo
termux-reload-settings

